(function(){
'use strict';
const VERSION='4.0.0';
const STORE_KEY='kidoraQuestDataV4';
const SESSION_KEY='kidoraQuestSessionV4';
const $=(id)=>document.getElementById(id);
const esc=(v)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=(p='id')=>p+'_'+Math.random().toString(36).slice(2,9)+'_'+Date.now().toString(36).slice(-4);
const today=()=>new Date().toISOString().slice(0,10);
const now=()=>new Date().toLocaleString();

const seedThemes=[
 {id:'colors',title:'Rainbow Bridge',icon:'🌈',level:'Early Beginner',words:['red','blue','yellow','green','purple','orange'],phonics:['r','b','y','g'],sentences:['I see red.','The ball is blue.','I like yellow.'],story:'The Rainbow Bridge is quiet. KIDORA needs red, blue, yellow, and green stars to make it shine again.',game:'Collect colour stars and say each colour aloud.',writingFrame:'I see ___.'},
 {id:'animals',title:'Animal Island',icon:'🐾',level:'Early Beginner',words:['cat','dog','bird','fish','rabbit','lion'],phonics:['c','d','b','f'],sentences:['I see a cat.','The dog can run.','The bird can sing.'],story:'Animal Island has lost its sounds. Help each animal find its voice by listening, speaking, reading, and writing.',game:'Match each animal to its sound and home.',writingFrame:'I see a ___.'},
 {id:'food',title:'Picnic Planet',icon:'🍎',level:'Beginner',words:['apple','banana','rice','milk','cake','water'],phonics:['a','b','m','w'],sentences:['I like apples.','I drink water.','This cake is sweet.'],story:'The Picnic Planet needs healthy food words. Children build a picnic basket with English words.',game:'Feed the picnic basket with the correct word cards.',writingFrame:'I like ___.'},
 {id:'family',title:'Family Tree House',icon:'🏡',level:'Beginner',words:['mother','father','sister','brother','baby','grandma'],phonics:['m','f','s','b'],sentences:['This is my mother.','I love my family.','My brother is kind.'],story:'The Family Tree House grows when children say and write family words with care.',game:'Place family members in the tree house.',writingFrame:'This is my ___.'},
 {id:'body',title:'Move-and-Say Mountain',icon:'🕺',level:'Beginner',words:['head','hand','leg','eye','ear','nose'],phonics:['h','l','e','n'],sentences:['Touch your head.','Clap your hands.','I have two eyes.'],story:'The mountain wakes up when children listen to body commands and move the KIDORA character.',game:'Follow the body command and tap the correct body part.',writingFrame:'This is my ___.'},
 {id:'weather',title:'Weather Sky Lab',icon:'☀️',level:'Beginner',words:['sunny','rainy','cloudy','windy','hot','cold'],phonics:['s','r','c','w'],sentences:['It is sunny.','It is rainy today.','I feel cold.'],story:'The sky has many moods. Help KIDORA read the weather signs and make a sky report.',game:'Choose the right weather symbol after listening.',writingFrame:'It is ___.'},
 {id:'classroom',title:'Classroom Castle',icon:'🎒',level:'Beginner',words:['book','pencil','bag','chair','table','eraser'],phonics:['b','p','t','e'],sentences:['This is my book.','I have a pencil.','The bag is red.'],story:'Classroom Castle opens only when children name, read, and write classroom objects.',game:'Find school things hidden in the castle.',writingFrame:'This is my ___.'},
 {id:'actions',title:'Action River',icon:'🏃',level:'Lower Primary',words:['run','jump','sing','read','write','draw'],phonics:['r','j','s','d'],sentences:['I can run.','I can sing.','I can read and write.'],story:'Action River moves when children listen to action words, act them out, and write action sentences.',game:'Build an action sentence train.',writingFrame:'I can ___.'}
];

function defaultData(){
 return {
  version:VERSION,
  settings:{adminPin:'2026',voiceRecording:true,theme:'Wonder Storyworld',schoolName:'KIDORA Quest Field Learning Lab',copyright:'© 2026 KIDORA Quest. Copyright Dr. Joko Slamet. All rights reserved.',requireApproval:false},
  users:[
   {id:'stu1',role:'student',name:'Alya Prameswari',email:'student@kidora.local',password:'student2026',avatar:'🦊',status:'approved',classId:'class1',parentId:'par1',level:'Early Beginner'},
   {id:'stu2',role:'student',name:'Bima Ardhana',email:'bima@kidora.local',password:'bima2026',avatar:'🐯',status:'approved',classId:'class1',parentId:'par1',level:'Beginner'},
   {id:'stu3',role:'student',name:'Citra Lestari',email:'citra@kidora.local',password:'citra2026',avatar:'🐼',status:'approved',classId:'class1',parentId:'par1',level:'Beginner'},
   {id:'tea1',role:'teacher',name:'Teacher KIDORA',email:'teacher@kidora.local',password:'teacher2026',avatar:'🧑‍🏫',status:'approved',classId:'class1'},
   {id:'par1',role:'parent',name:'Family Guardian',email:'parent@kidora.local',password:'parent2026',avatar:'👨‍👩‍👧',status:'approved',childIds:['stu1','stu2','stu3']}
  ],
  classes:[{id:'class1',name:'Young Explorers A',teacherId:'tea1',studentIds:['stu1','stu2','stu3']}],
  themes:seedThemes,
  quests:seedThemes.map((t,i)=>({id:'quest_'+t.id,title:t.title+' Quest',themeId:t.id,status:'approved',createdBy:'system',level:t.level,steps:['Hear the clue','Move the object','Say the sentence','Read the word path','Create story evidence','Share to portfolio'],date:today(),description:t.story})),
  progress:{
   stu1:{points:220,badges:['Sound Star','Echo Brave','Glyph Grower'],completed:['colors'],currentTheme:'animals'},
   stu2:{points:145,badges:['Sound Star','Story Seed'],completed:['colors'],currentTheme:'food'},
   stu3:{points:188,badges:['Echo Brave','Writing Wizard'],completed:['animals'],currentTheme:'colors'}
  },
  evidence:[
   {id:'ev1',studentId:'stu1',type:'listening',themeId:'colors',title:'Identified colour words',score:5,total:6,date:today(),note:'Completed SoundQuest with picture support.'},
   {id:'ev2',studentId:'stu1',type:'reading',themeId:'animals',title:'Read animal words',score:4,total:6,date:today(),note:'Read cat, dog, bird, fish.'},
   {id:'ev3',studentId:'stu2',type:'writing',themeId:'food',title:'Food sentence building',score:3,total:4,date:today(),note:'Built sentence: I like apples.'},
   {id:'ev4',studentId:'stu3',type:'speaking',themeId:'animals',title:'Animal sentence recording',score:4,total:5,date:today(),note:'Recorded: I see a cat.'}
  ],
  safetyQueue:[
   {id:'safe1',title:'AI Generated Weather Quest',type:'quest',status:'pending',content:'It is sunny. It is rainy. Children listen, say, read, and write weather words.',createdBy:'Teacher KIDORA',date:today()}
  ],
  logs:[{date:now(),event:'KIDORA Quest seeded with complete demo content and role dashboards.'}]
 };
}

const App={
 data:null,session:null,page:'home',roleChoice:'student',currentTheme:'colors',currentRecording:null,recorder:null,chunks:[],audio:null,builderWords:[],canvasReady:false,
 init(){
  this.data=this.load();
  this.session=this.loadSession();
  if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}
  window.addEventListener('beforeunload',()=>this.stopAll());
  if(this.session?.role){this.renderDashboard(this.session.role,'home');}else{this.renderLanding();}
 },
 load(){
  try{const raw=localStorage.getItem(STORE_KEY);if(raw){const d=JSON.parse(raw);if(d.version===VERSION)return d;}}
  catch(e){}
  const d=defaultData();localStorage.setItem(STORE_KEY,JSON.stringify(d));return d;
 },
 save(){localStorage.setItem(STORE_KEY,JSON.stringify(this.data));},
 loadSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');}catch(e){return null;}},
 saveSession(){sessionStorage.setItem(SESSION_KEY,JSON.stringify(this.session));},
 toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),2600);},
 user(){return this.data.users.find(u=>u.id===this.session?.userId)||null;},
 students(){return this.data.users.filter(u=>u.role==='student');},
 theme(id){return this.data.themes.find(t=>t.id===id)||this.data.themes[0];},
 studentTheme(studentId){return this.theme(this.data.progress[studentId]?.currentTheme||this.currentTheme||'colors');},
 points(studentId){return this.data.progress[studentId]?.points||0;},
 addPoints(studentId,points,badge){const p=this.data.progress[studentId]||(this.data.progress[studentId]={points:0,badges:[],completed:[],currentTheme:'colors'});p.points=(p.points||0)+points;if(badge&&!p.badges.includes(badge))p.badges.push(badge);this.save();},
 log(event){this.data.logs.unshift({date:now(),event});this.data.logs=this.data.logs.slice(0,80);this.save();},
 render(html){$('app').innerHTML=html;},
 renderLanding(){
  const areas=[['🌳','SoundQuest','AI listening, songs, stories, commands'],['🪞','EchoMirror','voice recording and speaking evidence'],['🌱','GlyphPath','phonics, words, phrases, story reading'],['✍️','StoryForge','tracing, drawing, sentence creation'],['🧩','Puzzle Bridge','integrated four-skill missions'],['📚','Living Storybook','portfolio of voice, writing, drawing'],['🧑‍🏫','Teacher Cockpit','quest design, reports, research analytics'],['🔐','Admin Control','PIN-protected full system control']];
  this.render(`<main class="landing">
   <section class="landing-left">
    <div class="brand-row"><div class="logo-mark">K</div><div><div class="brand-title">KIDORA Quest</div><div class="brand-sub">AI Integrated English Storyworld</div></div></div>
    <div class="hero-card">
     <h1 class="hero-title">Hear. Speak. Read. Write. <span>Create.</span></h1>
     <p class="hero-copy">A game-based learning world for young learners where every voice, word, sentence, drawing, and quest becomes learning evidence. Designed for integrated English skills, child-safe AI support, teacher control, parent visibility, and research-ready analytics.</p>
     <div class="hero-actions">
      <button class="primary-btn" onclick="App.openLogin()">Enter Learning World</button>
      <button class="secondary-btn" onclick="App.openAdminPin()">Admin PIN</button>
      <button class="ghost-btn" onclick="App.previewTour()">Preview Main Areas</button>
     </div>
     <div class="main-areas">${areas.map(a=>`<div class="area-chip"><div class="area-icon">${a[0]}</div><b>${a[1]}</b><span>${a[2]}</span></div>`).join('')}</div>
    </div>
   </section>
   <section class="landing-right">
    <div class="stage"><div class="storybook-visual">
     <div class="island i1"></div><div class="island i2"></div><div class="island i3"></div>
     <div class="path-dot d1"></div><div class="path-dot d2"></div><div class="path-dot d3"></div>
     <div class="kidora-creature"><div class="creature-mouth"></div></div>
     <div class="float-card fc1">🎧 Sound Forest</div><div class="float-card fc2">🪞 Echo Valley</div><div class="float-card fc3">📚 Storybook</div>
    </div></div>
   </section>
   <div class="copyright">${esc(this.data.settings.copyright)}</div>
  </main>`);
 },
 previewTour(){
  this.openModal(`<h2>KIDORA Quest Main Areas</h2><p class="login-helper">Production preview of the complete feature map. Login is required to save data.</p>
  <div class="grid two" style="margin-top:14px">${[
   ['🌳 SoundQuest AI','Listening with play, stop, story clues, sound commands, word matching, attempt tracking.'],
   ['🪞 EchoMirror AI','Speaking with target audio, start/stop recording, playback, clear voice, save voice evidence.'],
   ['🌱 GlyphPath AI','Reading with phonics, word cards, read-aloud support, matching and sentence path.'],
   ['✍️ StoryForge AI','Drawing canvas, sentence builder, tracing board, save writing evidence.'],
   ['🧑‍🏫 Teacher Cockpit','QuestWeaver AI, content creation, evidence review, parent reports, CSV exports.'],
   ['🔐 Admin Control','PIN 2026; full user, content, quest, safety, analytics and setting control.']
  ].map(x=>`<div class="admin-block"><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div><div class="modal-actions"><button class="primary-btn" onclick="App.closeModal()">Close</button></div>`);
 },
 openModal(content){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal">${content}</div></div>`);},
 closeModal(){const m=$('modal');if(m)m.remove();},
 openLogin(role='student'){
  this.roleChoice=role;
  this.openModal(`<h2>Enter KIDORA Quest</h2><p class="login-helper">Choose your workspace and sign in. Public landing information is intentionally hidden for production presentation.</p>
   <div class="role-tiles">${['student','teacher','parent'].map(r=>`<button class="role-tile ${r===role?'active':''}" onclick="App.closeModal();App.openLogin('${r}')">${r==='student'?'🧒 Student':r==='teacher'?'🧑‍🏫 Teacher':'👨‍👩‍👧 Parent'}</button>`).join('')}</div>
   <div class="form-grid">
    <div class="field"><label>Email</label><input id="loginEmail" type="email" autocomplete="username"></div>
    <div class="field"><label>Password</label><input id="loginPassword" type="password" autocomplete="current-password"></div>
   </div>
   <div class="modal-actions"><button class="ghost-btn" onclick="App.closeModal()">Cancel</button><button class="primary-btn" onclick="App.login('${role}')">Enter ${role.charAt(0).toUpperCase()+role.slice(1)} Dashboard</button></div>`);
  setTimeout(()=>$('loginEmail')?.focus(),50);
 },
 login(role){
  const email=$('loginEmail')?.value.trim().toLowerCase();const pass=$('loginPassword')?.value;
  const u=this.data.users.find(x=>x.role===role&&x.email.toLowerCase()===email&&x.password===pass&&x.status==='approved');
  if(!u){this.toast('Login not accepted. Check role, email, password, or approval status.');return;}
  this.session={role,uName:u.name,userId:u.id,date:Date.now()};this.saveSession();this.closeModal();this.renderDashboard(role,'home');this.log(`${u.name} opened ${role} dashboard.`);
 },
 openAdminPin(){
  this.openModal(`<h2>Admin Control PIN</h2><p class="login-helper">Admin access is PIN-protected for authorized system control.</p>
   <div class="field"><label>Admin PIN</label><input id="adminPin" type="password" inputmode="numeric" autocomplete="off"></div>
   <div class="modal-actions"><button class="ghost-btn" onclick="App.closeModal()">Cancel</button><button class="secondary-btn" onclick="App.loginAdminPin()">Open Admin Dashboard</button></div>`);
  setTimeout(()=>$('adminPin')?.focus(),50);
 },
 loginAdminPin(){
  const pin=$('adminPin')?.value.trim();
  if(pin!==String(this.data.settings.adminPin)){this.toast('Incorrect admin PIN.');return;}
  this.session={role:'admin',uName:'Administrator',userId:'admin',date:Date.now()};this.saveSession();this.closeModal();this.renderDashboard('admin','home');this.log('Admin dashboard opened with PIN.');
 },
 logout(){this.stopAll();sessionStorage.removeItem(SESSION_KEY);this.session=null;this.page='home';this.renderLanding();},
 renderDashboard(role,page='home'){
  this.page=page;const u=this.user();const title=role==='admin'?'Administrator':esc(u?.name||'KIDORA User');
  this.render(`<div class="app-shell"><header class="topbar"><div class="topbar-left"><div class="small-logo">K</div><div><div class="topbar-title">KIDORA Quest</div><div class="topbar-sub">${title} • ${role.toUpperCase()} WORKSPACE</div></div></div><div class="topbar-actions"><button class="mini-btn" onclick="App.stopAll()">⏹ Stop Audio</button><button class="ghost-btn" onclick="App.logout()">Logout</button></div></header><div class="layout"><aside class="sidebar">${this.nav(role).map(n=>`<button class="nav-btn ${page===n.id?'active':''}" onclick="App.renderDashboard('${role}','${n.id}')"><span>${n.icon}</span>${n.label}</button>`).join('')}</aside><main class="main">${this.renderPage(role,page)}</main></div></div>`);
  setTimeout(()=>this.afterRender(),60);
 },
 nav(role){
  if(role==='student')return [
   {id:'home',icon:'🗺️',label:'Quest Map'},{id:'sound',icon:'🌳',label:'SoundQuest'},{id:'speak',icon:'🪞',label:'EchoMirror'},{id:'read',icon:'🌱',label:'GlyphPath'},{id:'write',icon:'✍️',label:'StoryForge'},{id:'bridge',icon:'🧩',label:'Puzzle Bridge'},{id:'portfolio',icon:'📚',label:'Living Storybook'},{id:'treasure',icon:'🏆',label:'Treasure Room'}];
  if(role==='teacher')return [
   {id:'home',icon:'📊',label:'Teacher Cockpit'},{id:'designer',icon:'✨',label:'QuestWeaver AI'},{id:'content',icon:'🧰',label:'Content Studio'},{id:'evidence',icon:'📚',label:'Evidence Review'},{id:'reports',icon:'📝',label:'Reports AI'},{id:'analytics',icon:'🔬',label:'Research Cockpit'}];
  if(role==='parent')return [
   {id:'home',icon:'🏡',label:'Family Window'},{id:'storybook',icon:'📚',label:'Storybook View'},{id:'practice',icon:'💡',label:'Home Practice AI'},{id:'report',icon:'🌱',label:'Growth Report'}];
  return [{id:'home',icon:'🔐',label:'Admin Control'},{id:'users',icon:'👥',label:'Users'},{id:'contents',icon:'🧰',label:'Contents'},{id:'quests',icon:'🗺️',label:'Quests'},{id:'safety',icon:'🛡️',label:'AI Safety'},{id:'analytics',icon:'📈',label:'Analytics'},{id:'settings',icon:'⚙️',label:'Settings'}];
 },
 renderPage(role,page){
  if(role==='student')return this.studentPage(page);
  if(role==='teacher')return this.teacherPage(page);
  if(role==='parent')return this.parentPage(page);
  return this.adminPage(page);
 },
 head(title,sub,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div>${action}</div></div>`;},
 studentPage(page){
  const u=this.user();const theme=this.studentTheme(u.id);
  if(page==='home')return this.studentHome(u,theme);
  if(page==='sound')return this.soundQuest(theme,u);
  if(page==='speak')return this.echoMirror(theme,u);
  if(page==='read')return this.glyphPath(theme,u);
  if(page==='write')return this.storyForge(theme,u);
  if(page==='bridge')return this.puzzleBridge(theme,u);
  if(page==='portfolio')return this.portfolio(u);
  if(page==='treasure')return this.treasure(u);
  return '';
 },
 studentHome(u,theme){
  const p=this.data.progress[u.id]||{};const ev=this.data.evidence.filter(e=>e.studentId===u.id);
  return `${this.head('My Quest Map',`Welcome ${esc(u.name)}. Complete quests by listening, speaking, reading, writing, creating, and sharing.`)}
  <div class="grid four"><div class="card metric"><div class="metric-icon">⭐</div><div><b>${p.points||0}</b><span>Quest Points</span></div></div><div class="card metric"><div class="metric-icon">🏅</div><div><b>${(p.badges||[]).length}</b><span>Badges</span></div></div><div class="card metric"><div class="metric-icon">📚</div><div><b>${ev.length}</b><span>Portfolio Evidence</span></div></div><div class="card metric"><div class="metric-icon">${theme.icon}</div><div><b>${esc(theme.title)}</b><span>Current Quest</span></div></div></div>
  <div class="card" style="margin-top:16px"><h2>Choose Your Main Area</h2><div class="quest-map">${[
   ['sound','🌳','SoundQuest','Listen to clues, songs, word sounds, and commands.'],['speak','🪞','EchoMirror','Record your voice and make story characters speak.'],['read','🌱','GlyphPath','Grow letters into words, sentences, and story paths.'],['write','✍️','StoryForge','Trace, draw, label, build sentences, and make storybook pages.'],['bridge','🧩','Puzzle Bridge','Use all four skills to solve one complete mission.'],['portfolio','📚','Living Storybook','See your saved voice, reading, writing, and drawing evidence.']
  ].map(x=>`<div class="quest-node"><div class="big">${x[1]}</div><h3>${x[2]}</h3><p>${x[3]}</p><button class="primary-btn" onclick="App.renderDashboard('student','${x[0]}')">Open</button></div>`).join('')}</div></div>
  <div class="grid two" style="margin-top:16px"><div class="card"><h2>Active Storyworld</h2><p><b>${theme.icon} ${esc(theme.title)}</b></p><p>${esc(theme.story)}</p><div class="pill-row">${theme.words.map(w=>`<span class="pill">${esc(w)}</span>`).join('')}</div></div><div class="card"><h2>Daily AI Guidance</h2><p>${this.aiStudentHint(u.id,theme.id)}</p><div class="sound-bars"><i></i><i></i><i></i><i></i></div></div></div>`;
 },
 aiStudentHint(studentId,themeId){
  const ev=this.data.evidence.filter(e=>e.studentId===studentId&&e.themeId===themeId);const types=new Set(ev.map(e=>e.type));
  if(!types.has('listening'))return 'Start with SoundQuest. Listen carefully, tap the correct picture, and save one listening evidence.';
  if(!types.has('speaking'))return 'Move to EchoMirror. Record one sentence and listen to your own voice.';
  if(!types.has('reading'))return 'Open GlyphPath. Read the word cards and build one sentence path.';
  if(!types.has('writing'))return 'Finish with StoryForge. Draw, label, and save a page to your Living Storybook.';
  return 'Excellent. Try Puzzle Bridge to combine all four English skills in one mission.';
 },
 themeSelector(role='student'){return `<select id="themeSelect" onchange="App.changeTheme(this.value)">${this.data.themes.map(t=>`<option value="${t.id}" ${t.id===this.currentTheme?'selected':''}>${t.icon} ${esc(t.title)}</option>`).join('')}</select>`;},
 changeTheme(id){this.currentTheme=id;const u=this.user();if(u?.role==='student'){const p=this.data.progress[u.id]||(this.data.progress[u.id]={points:0,badges:[],completed:[],currentTheme:id});p.currentTheme=id;this.save();this.renderDashboard('student',this.page);}else{this.renderDashboard(this.session.role,this.page);} },
 soundQuest(theme,u){
  const choices=theme.words.slice(0,4);
  return `${this.head('SoundQuest AI','Listening studio with real play, stop, word, command, story, and evidence saving.',`<div class="field">${this.themeSelector()}</div>`)}
  <div class="skill-hero"><section class="card"><h2>${theme.icon} ${esc(theme.title)} Listening Mission</h2><p>${esc(theme.story)}</p><div class="activity-row"><button class="primary-btn" onclick="App.speakText('${esc(theme.story)}')">▶ Play Story</button><button class="ghost-btn" onclick="App.stopAll()">⏹ Stop</button><button class="secondary-btn" onclick="App.speakText('Listen carefully. Find the word ${esc(choices[0])}.')">🔊 Play Clue</button></div><h3>Listen and Tap</h3><p>Play a target word, then tap the correct card. The system records attempts and saves evidence.</p><div class="choice-grid" id="listeningChoices">${choices.map((w,i)=>`<button class="choice-btn" onclick="App.checkListening('${w}','${choices[0]}',this)"><span style="font-size:28px">${this.wordIcon(w)}</span><br>${esc(w)}</button>`).join('')}</div><div class="activity-row"><button class="primary-btn" onclick="App.speakText('${choices[0]}')">▶ Play Target Word</button><button class="ghost-btn" onclick="App.stopAll()">⏹ Stop Word</button><button class="secondary-btn" onclick="App.saveEvidence('${u.id}','listening','${theme.id}','SoundQuest: ${esc(theme.title)}',5,6,'Child completed listen-and-tap and story clue activity.')">💾 Save Listening Evidence</button></div></section><aside class="card"><h2>Listening Content Bank</h2><div class="content-list">${theme.words.map(w=>`<div class="content-item"><div><strong>${this.wordIcon(w)} ${esc(w)}</strong><span>Word audio + picture clue</span></div><button class="mini-btn" onclick="App.speakText('${esc(w)}')">Play</button></div>`).join('')}</div><h3 style="margin-top:16px">Commands</h3><div class="pill-row">${['Tap '+choices[0], 'Find '+choices[1], 'Move '+choices[2], 'Say '+choices[3]].map(c=>`<button class="pill" onclick="App.speakText('${esc(c)}')">${esc(c)}</button>`).join('')}</div></aside></div>`;
 },
 checkListening(word,target,btn){
  document.querySelectorAll('#listeningChoices .choice-btn').forEach(b=>b.classList.remove('correct','wrong'));
  if(word===target){btn.classList.add('correct');this.toast('Great listening. You found '+target+'.');this.speakText('Great listening. You found '+target+'.');this.addPoints(this.user().id,10,'Sound Star');}
  else{btn.classList.add('wrong');this.toast('Try again. Listen carefully.');this.speakText('Try again. Listen carefully.');}
 },
 wordIcon(w){const map={red:'🔴',blue:'🔵',yellow:'🟡',green:'🟢',purple:'🟣',orange:'🟠',cat:'🐱',dog:'🐶',bird:'🐦',fish:'🐟',rabbit:'🐰',lion:'🦁',apple:'🍎',banana:'🍌',rice:'🍚',milk:'🥛',cake:'🍰',water:'💧',mother:'👩',father:'👨',sister:'👧',brother:'👦',baby:'👶',grandma:'👵',head:'🙂',hand:'✋',leg:'🦵',eye:'👁️',ear:'👂',nose:'👃',sunny:'☀️',rainy:'🌧️',cloudy:'☁️',windy:'🌬️',hot:'🔥',cold:'❄️',book:'📘',pencil:'✏️',bag:'🎒',chair:'🪑',table:'🟫',eraser:'🧽',run:'🏃',jump:'🦘',sing:'🎤',read:'📖',write:'✍️',draw:'🎨'};return map[w]||'✨';},
 echoMirror(theme,u){const phrase=theme.sentences[0];
  return `${this.head('EchoMirror AI','Speaking studio with target audio, recording, playback, clear voice, and portfolio evidence.',`<div class="field">${this.themeSelector()}</div>`)}
  <div class="grid two"><div class="card"><h2>Voice Mission</h2><p>Target sentence:</p><div class="admin-block"><h2>${esc(phrase)}</h2></div><div class="activity-row"><button class="primary-btn" onclick="App.speakText('${esc(phrase)}')">▶ Play Target</button><button class="ghost-btn" onclick="App.stopAll()">⏹ Stop Target</button></div><h3>Record Your Voice</h3><p>Allow microphone permission. Recording works after deployment on HTTPS GitHub Pages.</p><div class="activity-row"><button class="secondary-btn" onclick="App.startRecording()">🎙 Start Record</button><button class="danger-btn" onclick="App.stopRecording()">⏹ Stop Record</button><button class="ghost-btn" onclick="App.playRecording()">▶ Play My Voice</button><button class="ghost-btn" onclick="App.clearRecording()">Clear Voice</button></div><div id="recordStatus" class="empty">No voice recorded yet.</div><div class="activity-row"><button class="primary-btn" onclick="App.saveVoiceEvidence('${u.id}','${theme.id}','${esc(phrase)}')">💾 Save Speaking Evidence</button><button class="ghost-btn" onclick="App.speakText('Good try. Speak slowly and clearly. Your voice is growing.')">AI Gentle Feedback</button></div></div><div class="card"><h2>Speaking Prompts</h2><div class="content-list">${theme.sentences.map(s=>`<div class="content-item"><div><strong>${esc(s)}</strong><span>Repeat, record, and save</span></div><button class="mini-btn" onclick="App.speakText('${esc(s)}')">Play</button></div>`).join('')}</div><h3 style="margin-top:16px">Voice-to-World</h3><p>When saved, the child’s recording becomes a character voice artifact in the Living Storybook.</p></div></div>`;
 },
 glyphPath(theme,u){const words=theme.words.slice(0,6);const sentence=theme.sentences[1]||theme.sentences[0];
  return `${this.head('GlyphPath AI','Reading pathway from phonics to words, phrases, and short story sentences.',`<div class="field">${this.themeSelector()}</div>`)}
  <div class="grid two"><div class="card"><h2>Letter-Sound Garden</h2><p>Tap a phonics seed to hear the sound. Read the matching words.</p><div class="pill-row">${theme.phonics.map(p=>`<button class="pill" onclick="App.speakText('${p}')">/${esc(p)}/</button>`).join('')}</div><h2 style="margin-top:20px">Word Bloom Cards</h2><div class="choice-grid">${words.map(w=>`<button class="choice-btn" onclick="App.speakText('${esc(w)}')"><span style="font-size:32px">${this.wordIcon(w)}</span><br>${esc(w)}</button>`).join('')}</div><div class="activity-row"><button class="primary-btn" onclick="App.speakText('${esc(sentence)}')">▶ Read Sentence</button><button class="ghost-btn" onclick="App.stopAll()">⏹ Stop</button><button class="secondary-btn" onclick="App.saveEvidence('${u.id}','reading','${theme.id}','GlyphPath: ${esc(theme.title)}',5,6,'Child read phonics seeds, word cards, and sentence path.')">💾 Save Reading Evidence</button></div></div><div class="card"><h2>Sentence Path</h2><p>Read, listen, and build meaning.</p><div class="admin-block"><h2>${esc(sentence)}</h2></div><h3>Reading Levels</h3><div class="content-list">${['Picture + sound','Letter sound','Word card','Phrase','Short sentence','Mini story'].map((x,i)=>`<div class="content-item"><div><strong>Level ${i+1}</strong><span>${x}</span></div><span class="badge ${i<4?'ok':'warn'}">Available</span></div>`).join('')}</div><h3 style="margin-top:16px">Mini Story</h3><p>${esc(theme.story)}</p><button class="primary-btn" onclick="App.speakText('${esc(theme.story)}')">Read Mini Story Aloud</button></div></div>`;
 },
 storyForge(theme,u){
  const words=[...theme.writingFrame.replace('___',theme.words[0]).replace('.','').split(' ')];this.builderWords=words;
  return `${this.head('StoryForge AI','Writing, drawing, tracing, sentence building, and digital storybook creation.',`<div class="field">${this.themeSelector()}</div>`)}
  <div class="grid two"><div class="card"><h2>Drawing and Tracing Canvas</h2><p>Draw, trace, or label the target word: <b>${esc(theme.words[0])}</b></p><div class="canvas-wrap"><canvas id="drawingCanvas" class="drawing-canvas" width="900" height="420"></canvas></div><div class="activity-row"><button class="ghost-btn" onclick="App.clearCanvas()">Clear Canvas</button><button class="primary-btn" onclick="App.saveCanvasEvidence('${u.id}','${theme.id}')">💾 Save Drawing Evidence</button></div></div><div class="card"><h2>Sentence Train Builder</h2><p>Tap word tiles to build a sentence.</p><div id="sentenceBuilder" class="sentence-builder"></div><div class="word-bank" style="margin-top:12px">${words.sort(()=>Math.random()-.5).map(w=>`<button class="word-tile" onclick="App.addWordToBuilder('${esc(w)}')">${esc(w)}</button>`).join('')}</div><div class="activity-row"><button class="primary-btn" onclick="App.readBuiltSentence()">▶ Read My Sentence</button><button class="ghost-btn" onclick="App.clearBuilder()">Clear Sentence</button><button class="secondary-btn" onclick="App.saveWritingEvidence('${u.id}','${theme.id}')">💾 Save Writing Evidence</button></div><h3>AI Sentence Frames</h3><div class="pill-row">${[theme.writingFrame,'I like ___.','This is my ___.','The ___ is big.'].map(f=>`<button class="pill" onclick="App.speakText('${esc(f.replace('___',theme.words[0]))}')">${esc(f)}</button>`).join('')}</div></div></div>`;
 },
 addWordToBuilder(w){this.builderWords.push(w);this.updateBuilder();},
 updateBuilder(){const b=$('sentenceBuilder');if(b)b.innerHTML=this.builderWords.map((w,i)=>`<button class="word-tile" onclick="App.removeBuilderWord(${i})">${esc(w)}</button>`).join('');},
 removeBuilderWord(i){this.builderWords.splice(i,1);this.updateBuilder();},
 clearBuilder(){this.builderWords=[];this.updateBuilder();},
 readBuiltSentence(){const s=this.builderWords.join(' ');if(!s){this.toast('Build a sentence first.');return;}this.speakText(s);},
 puzzleBridge(theme,u){return `${this.head('Puzzle Bridge','One mission that requires listening, speaking, reading, writing, and sharing evidence.',`<div class="field">${this.themeSelector()}</div>`)}<div class="card"><h2>${theme.icon} Integrated Mission: ${esc(theme.title)}</h2><p>${esc(theme.story)}</p><div class="grid three">${[
   ['1','Hear','Play the story clue and identify key words.',`App.speakText('${esc(theme.story)}')`],['2','Say','Record the target sentence in EchoMirror.',`App.renderDashboard('student','speak')`],['3','Read','Open the word path and read the cards.',`App.renderDashboard('student','read')`],['4','Create','Draw and build a sentence in StoryForge.',`App.renderDashboard('student','write')`],['5','Share','Save the mission to Living Storybook.',`App.saveEvidence('${u.id}','integrated','${theme.id}','Puzzle Bridge: ${esc(theme.title)}',6,6,'Child completed integrated four-skill mission.')`],['6','Unlock','Earn badge and points.',`App.completeQuest('${u.id}','${theme.id}')`]
  ].map(s=>`<div class="quest-node"><div class="big">${s[0]}</div><h3>${s[1]}</h3><p>${s[2]}</p><button class="primary-btn" onclick="${s[3]}">${s[1]}</button></div>`).join('')}</div></div>`;},
 completeQuest(studentId,themeId){const p=this.data.progress[studentId]||(this.data.progress[studentId]={points:0,badges:[],completed:[],currentTheme:themeId});if(!p.completed.includes(themeId))p.completed.push(themeId);this.addPoints(studentId,50,'Quest Master');this.save();this.toast('Quest completed. New badge unlocked.');this.renderDashboard('student','treasure');},
 portfolio(u){const ev=this.data.evidence.filter(e=>e.studentId===u.id);
  return `${this.head('Living Storybook','Saved evidence from listening, speaking, reading, writing, drawing, and integrated quests.')}<div class="grid two">${ev.length?ev.map(e=>this.evidenceCard(e)).join(''):'<div class="empty">No evidence yet. Open a skill area and save your first artifact.</div>'}</div>`;},
 evidenceCard(e){const t=this.theme(e.themeId);return `<div class="evidence-card"><div class="split"><div><span class="badge ok">${esc(e.type)}</span><h3>${esc(e.title)}</h3></div><div style="font-size:30px">${t.icon}</div></div><p>${esc(e.note||'')}</p><p><b>Score:</b> ${e.score||0}/${e.total||0} • <b>Date:</b> ${esc(e.date||'')}</p>${e.audio?`<audio controls src="${e.audio}" style="width:100%"></audio>`:''}${e.image?`<img src="${e.image}" alt="saved drawing" style="width:100%;border-radius:18px;border:1px solid var(--line)">`:''}${e.text?`<div class="admin-block"><b>Text:</b> ${esc(e.text)}</div>`:''}</div>`;},
 treasure(u){const p=this.data.progress[u.id]||{points:0,badges:[]};return `${this.head('Treasure Room','Badges, points, rewards, and printable Quest Mastery Passport.')}<div class="grid two"><div class="card"><h2>My Rewards</h2><div class="metric"><div class="metric-icon">⭐</div><div><b>${p.points||0}</b><span>Total points</span></div></div><h3>Badges</h3><div class="pill-row">${(p.badges||[]).map(b=>`<span class="pill">🏅 ${esc(b)}</span>`).join('')||'<span class="empty">No badges yet.</span>'}</div></div><div class="card"><div class="certificate"><h2>KIDORA Quest</h2><p>Quest Mastery Passport</p><h3>${esc(u.name)}</h3><p>has participated in integrated English quests through listening, speaking, reading, writing, and story creation.</p><p><b>Points:</b> ${p.points||0}</p><p>${esc(this.data.settings.copyright)}</p></div><div class="activity-row no-print"><button class="primary-btn" onclick="window.print()">Print Certificate</button></div></div></div>`;},
 saveEvidence(studentId,type,themeId,title,score,total,note){this.data.evidence.unshift({id:uid('ev'),studentId,type,themeId,title,score,total,note,date:today()});this.addPoints(studentId,12,type==='listening'?'Sound Star':type==='reading'?'Glyph Grower':type==='writing'?'Writing Wizard':type==='speaking'?'Echo Brave':'Story Seed');this.save();this.toast('Evidence saved to Living Storybook.');},
 saveVoiceEvidence(studentId,themeId,text){if(!this.currentRecording){this.toast('Record your voice first.');return;}this.data.evidence.unshift({id:uid('ev'),studentId,type:'speaking',themeId,title:'EchoMirror voice evidence',score:5,total:5,note:'Child recorded target sentence and saved voice evidence.',text,audio:this.currentRecording,date:today()});this.addPoints(studentId,15,'Echo Brave');this.save();this.toast('Voice evidence saved.');},
 saveCanvasEvidence(studentId,themeId){const c=$('drawingCanvas');if(!c){return;}const img=c.toDataURL('image/png');this.data.evidence.unshift({id:uid('ev'),studentId,type:'drawing',themeId,title:'StoryForge drawing evidence',score:5,total:5,note:'Child created drawing/tracing evidence on canvas.',image:img,date:today()});this.addPoints(studentId,15,'Creative Storymaker');this.save();this.toast('Drawing saved to Living Storybook.');},
 saveWritingEvidence(studentId,themeId){const text=this.builderWords.join(' ');if(!text){this.toast('Build a sentence first.');return;}this.data.evidence.unshift({id:uid('ev'),studentId,type:'writing',themeId,title:'StoryForge sentence evidence',score:5,total:5,note:'Child built a sentence using word tiles.',text,date:today()});this.addPoints(studentId,15,'Writing Wizard');this.save();this.toast('Writing evidence saved.');},
 speakText(text){this.stopAll();if(!('speechSynthesis' in window)){this.toast('Speech synthesis is not supported in this browser.');return;}const u=new SpeechSynthesisUtterance(String(text).replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&amp;/g,'&'));u.lang='en-US';u.rate=.82;u.pitch=1.12;this.audio=u;window.speechSynthesis.speak(u);},
 stopAll(){try{window.speechSynthesis?.cancel();}catch(e){} if(this.recordedAudio){this.recordedAudio.pause();this.recordedAudio.currentTime=0;}},
 async startRecording(){
  if(!this.data.settings.voiceRecording){this.toast('Voice recording is disabled by admin.');return;}
  if(!navigator.mediaDevices?.getUserMedia){this.toast('This browser does not support microphone recording.');return;}
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});this.chunks=[];this.recorder=new MediaRecorder(stream);this.recorder.ondataavailable=e=>{if(e.data.size>0)this.chunks.push(e.data);};this.recorder.onstop=()=>{const blob=new Blob(this.chunks,{type:'audio/webm'});const reader=new FileReader();reader.onload=()=>{this.currentRecording=reader.result;const st=$('recordStatus');if(st)st.innerHTML='<span class="badge ok">Voice recorded</span> Ready to play or save.';};reader.readAsDataURL(blob);stream.getTracks().forEach(t=>t.stop());};this.recorder.start();const st=$('recordStatus');if(st)st.innerHTML='<span class="badge warn">Recording...</span> Speak clearly, then press Stop Record.';this.toast('Recording started.');}catch(e){this.toast('Microphone permission was not granted.');}
 },
 stopRecording(){if(this.recorder&&this.recorder.state!=='inactive'){this.recorder.stop();this.toast('Recording stopped.');}else{this.toast('No active recording.');}},
 playRecording(){if(!this.currentRecording){this.toast('No voice recorded yet.');return;}this.recordedAudio=new Audio(this.currentRecording);this.recordedAudio.play().catch(()=>this.toast('Could not play recording.'));},
 clearRecording(){this.currentRecording=null;const st=$('recordStatus');if(st)st.textContent='No voice recorded yet.';this.toast('Voice cleared.');},
 afterRender(){this.updateBuilder();this.initCanvas();},
 initCanvas(){const canvas=$('drawingCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.lineWidth=7;ctx.lineCap='round';ctx.strokeStyle='#6d4dfc';ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='bold 74px Arial';ctx.fillStyle='rgba(109,77,252,.13)';ctx.fillText('Trace • Draw • Label',70,140);let drawing=false;const pos=(e)=>{const r=canvas.getBoundingClientRect();const p=e.touches?e.touches[0]:e;return {x:(p.clientX-r.left)*(canvas.width/r.width),y:(p.clientY-r.top)*(canvas.height/r.height)}};const down=e=>{drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault();};const move=e=>{if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault();};const up=()=>{drawing=false;};canvas.onmousedown=down;canvas.onmousemove=move;window.onmouseup=up;canvas.ontouchstart=down;canvas.ontouchmove=move;canvas.ontouchend=up;},
 clearCanvas(){const c=$('drawingCanvas');if(c){const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fffdf6';ctx.fillRect(0,0,c.width,c.height);ctx.font='bold 74px Arial';ctx.fillStyle='rgba(109,77,252,.13)';ctx.fillText('Trace • Draw • Label',70,140);}},
 teacherPage(page){if(page==='home')return this.teacherHome();if(page==='designer')return this.questDesigner();if(page==='content')return this.teacherContent();if(page==='evidence')return this.teacherEvidence();if(page==='reports')return this.teacherReports();if(page==='analytics')return this.teacherAnalytics();return '';},
 teacherHome(){const students=this.students();return `${this.head('Teacher Quest Cockpit','Monitor every learner, skill evidence, AI quests, and portfolio growth.')}<div class="grid four"><div class="card metric"><div class="metric-icon">🧒</div><div><b>${students.length}</b><span>Students</span></div></div><div class="card metric"><div class="metric-icon">🗺️</div><div><b>${this.data.quests.length}</b><span>Quests</span></div></div><div class="card metric"><div class="metric-icon">📚</div><div><b>${this.data.evidence.length}</b><span>Evidence</span></div></div><div class="card metric"><div class="metric-icon">🛡️</div><div><b>${this.data.safetyQueue.filter(x=>x.status==='pending').length}</b><span>Pending AI Safety</span></div></div></div><div class="card" style="margin-top:16px"><h2>Class Progress Map</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Child</th><th>Level</th><th>Current Quest</th><th>Points</th><th>Evidence</th><th>AI Suggestion</th></tr></thead><tbody>${students.map(s=>{const t=this.studentTheme(s.id);return `<tr><td>${s.avatar} <b>${esc(s.name)}</b></td><td>${esc(s.level)}</td><td>${t.icon} ${esc(t.title)}</td><td>${this.points(s.id)}</td><td>${this.data.evidence.filter(e=>e.studentId===s.id).length}</td><td>${this.aiStudentHint(s.id,t.id)}</td></tr>`}).join('')}</tbody></table></div></div>`;},
 questDesigner(){return `${this.head('QuestWeaver AI','Generate child-safe integrated quests from teacher-selected theme, vocabulary, and learning objective.')}<div class="grid two"><div class="card"><h2>Create AI Quest</h2><div class="form-grid"><div class="field"><label>Theme Title</label><input id="qdTitle" value="Ocean Words Adventure"></div><div class="field"><label>Vocabulary</label><input id="qdWords" value="sea, fish, boat, blue, wave"></div><div class="field"><label>Sentence Pattern</label><input id="qdPattern" value="I see a ___"></div><div class="field"><label>Level</label><select id="qdLevel"><option>Early Beginner</option><option>Beginner</option><option>Lower Primary</option></select></div><div class="field"><label>Learning Goal</label><textarea id="qdGoal">Children listen to ocean words, record a sentence, read word cards, and create one labelled drawing.</textarea></div></div><div class="activity-row"><button class="primary-btn" onclick="App.generateQuestAI()">✨ Generate Quest</button><button class="secondary-btn" onclick="App.publishGeneratedQuest()">Publish Generated Quest</button></div></div><div class="card"><h2>Generated Quest Preview</h2><div id="generatedQuest" class="empty">AI-generated quest will appear here.</div></div></div>`;},
 generateQuestAI(){const title=$('qdTitle').value.trim();const words=$('qdWords').value.split(',').map(x=>x.trim()).filter(Boolean);const pattern=$('qdPattern').value.trim();const goal=$('qdGoal').value.trim();const level=$('qdLevel').value;const html=`<div class="admin-block"><h3>${esc(title)}</h3><p><b>Level:</b> ${esc(level)}</p><p><b>Story Problem:</b> KIDORA finds a hidden world where the words ${words.map(esc).join(', ')} are waiting to be heard, spoken, read, and written.</p><ol><li>SoundQuest: play and identify ${esc(words[0]||'target')}.</li><li>EchoMirror: record "${esc(pattern.replace('___',words[0]||'word'))}".</li><li>GlyphPath: read word cards and sentence path.</li><li>StoryForge: draw and label one object.</li><li>Puzzle Bridge: save evidence to Living Storybook.</li></ol><p><b>Teacher goal:</b> ${esc(goal)}</p></div>`;$('generatedQuest').innerHTML=html;this.generatedQuest={title,words,pattern,level,goal};this.toast('Quest generated locally.');},
 publishGeneratedQuest(){if(!this.generatedQuest){this.toast('Generate a quest first.');return;}const g=this.generatedQuest;const id=uid('theme');this.data.themes.push({id,title:g.title,icon:'🌊',level:g.level,words:g.words,phonics:g.words.map(w=>w[0]).slice(0,4),sentences:[g.pattern.replace('___',g.words[0]||'word'),`I like ${g.words[1]||'English'}.`],story:`KIDORA opens ${g.title}. Children listen, speak, read, write, create, and share a new story page.`,game:'Integrated AI quest game.',writingFrame:g.pattern});this.data.quests.unshift({id:uid('quest'),title:g.title+' Quest',themeId:id,status:'approved',createdBy:this.user()?.name||'Teacher',level:g.level,steps:['Hear','Move','Say','Read','Create','Share'],date:today(),description:g.goal});this.save();this.toast('Generated quest published to Content and Quest Library.');this.renderDashboard('teacher','content');},
 teacherContent(){return `${this.head('Content Studio','All skill contents are active and connected to child dashboards. Add themes, words, sentences, and stories.')}<div class="grid two"><div class="card"><h2>Add Content Theme</h2><div class="form-grid"><div class="field"><label>Title</label><input id="ctTitle" placeholder="Space Adventure"></div><div class="field"><label>Icon</label><input id="ctIcon" value="🚀"></div><div class="field"><label>Words comma separated</label><input id="ctWords" placeholder="moon, star, sun"></div><div class="field"><label>Sentences separated by |</label><input id="ctSent" placeholder="I see the moon.|The star is bright."></div><div class="field"><label>Story</label><textarea id="ctStory" placeholder="Short child-safe story..."></textarea></div></div><button class="primary-btn" onclick="App.addThemeFromForm(App.session.role)">Add Theme</button></div><div class="card"><h2>Active Theme Bank</h2><div class="content-list">${this.data.themes.map(t=>`<div class="content-item"><div><strong>${t.icon} ${esc(t.title)}</strong><span>${t.words.length} words • ${t.sentences.length} sentences • ${esc(t.level)}</span></div><button class="mini-btn" onclick="App.previewTheme('${t.id}')">Preview</button></div>`).join('')}</div></div></div>`;},
 previewTheme(id){const t=this.theme(id);this.openModal(`<h2>${t.icon} ${esc(t.title)}</h2><p>${esc(t.story)}</p><h3>Words</h3><div class="pill-row">${t.words.map(w=>`<span class="pill">${esc(w)}</span>`).join('')}</div><h3>Sentences</h3><div class="content-list">${t.sentences.map(s=>`<div class="content-item"><strong>${esc(s)}</strong><button class="mini-btn" onclick="App.speakText('${esc(s)}')">Play</button></div>`).join('')}</div><div class="modal-actions"><button class="primary-btn" onclick="App.closeModal()">Close</button></div>`);},
 addThemeFromForm(role){const title=$('ctTitle')?.value.trim();const icon=$('ctIcon')?.value.trim()||'✨';const words=($('ctWords')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);const sentences=($('ctSent')?.value||'').split('|').map(x=>x.trim()).filter(Boolean);const story=$('ctStory')?.value.trim();if(!title||!words.length||!sentences.length||!story){this.toast('Complete title, words, sentences, and story.');return;}const id=uid('theme');this.data.themes.push({id,title,icon,level:'Teacher Created',words,phonics:words.map(w=>w[0]).slice(0,4),sentences,story,game:'Teacher-created integrated game.',writingFrame:'I see ___.'});this.data.quests.unshift({id:uid('quest'),title:title+' Quest',themeId:id,status:'approved',createdBy:this.user()?.name||'Admin',level:'Teacher Created',steps:['Hear','Say','Read','Create','Share'],date:today(),description:story});this.save();this.toast('Content theme added and connected to skill modules.');this.renderDashboard(this.session.role,role==='admin'?'contents':'content');},
 teacherEvidence(){const ev=this.data.evidence;return `${this.head('Evidence Review','Review voice, listening, reading, writing, drawing, and integrated portfolio artifacts.')}<div class="grid two">${ev.map(e=>this.evidenceCardWithStudent(e)).join('')||'<div class="empty">No evidence yet.</div>'}</div>`;},
 evidenceCardWithStudent(e){const s=this.data.users.find(u=>u.id===e.studentId);return `<div class="evidence-card"><p><span class="badge ok">${esc(e.type)}</span> ${s?.avatar||''} <b>${esc(s?.name||'Unknown')}</b></p>${this.evidenceCard(e)}</div>`;},
 teacherReports(){return `${this.head('Reports AI','Generate positive, editable child progress reports from portfolio evidence.')}<div class="grid two"><div class="card"><h2>Select Student</h2><div class="content-list">${this.students().map(s=>`<div class="content-item"><div><strong>${s.avatar} ${esc(s.name)}</strong><span>${this.data.evidence.filter(e=>e.studentId===s.id).length} evidence items</span></div><button class="mini-btn" onclick="App.generateReport('${s.id}')">Generate Report</button></div>`).join('')}</div></div><div class="card"><h2>AI Report Draft</h2><div id="reportDraft" class="empty">Choose a student to generate report.</div></div></div>`;},
 generateReport(studentId){const s=this.data.users.find(u=>u.id===studentId);const ev=this.data.evidence.filter(e=>e.studentId===studentId);const types=[...new Set(ev.map(e=>e.type))];const report=`<div class="admin-block"><h3>${esc(s.name)} – KIDORA Growth Report</h3><p>${esc(s.name)} has completed ${ev.length} portfolio evidence items across ${types.join(', ')||'early exploration'} activities. The child is developing integrated English skills through listening clues, speaking recordings, reading paths, writing tasks, and story creation.</p><p><b>Strength:</b> ${types.includes('speaking')?'Shows growing confidence in voice recording and oral repetition.':'Responds positively to visual and audio support.'}</p><p><b>Next support:</b> Continue short home practice using target words, repeated listening, and one simple sentence each day.</p><p><b>Suggested home sentence:</b> I see a ___.</p></div>`;$('reportDraft').innerHTML=report;},
 teacherAnalytics(){return `${this.head('Research Cockpit','Export data for field testing and monitor multimodal learning evidence.','<button class="primary-btn" onclick="App.exportCSV()">Export CSV</button>')}<div class="grid three">${['listening','speaking','reading','writing','drawing','integrated'].map(type=>`<div class="card metric"><div class="metric-icon">${this.typeIcon(type)}</div><div><b>${this.data.evidence.filter(e=>e.type===type).length}</b><span>${type} evidence</span></div></div>`).join('')}</div><div class="card" style="margin-top:16px"><h2>System Logs</h2><div class="content-list">${this.data.logs.map(l=>`<div class="content-item"><div><strong>${esc(l.event)}</strong><span>${esc(l.date)}</span></div></div>`).join('')}</div></div>`;},
 typeIcon(type){return {listening:'🎧',speaking:'🎙️',reading:'📖',writing:'✍️',drawing:'🎨',integrated:'🧩'}[type]||'✨';},
 parentPage(page){if(page==='home')return this.parentHome();if(page==='storybook')return this.parentStorybook();if(page==='practice')return this.parentPractice();if(page==='report')return this.parentReport();return '';},
 parentChildren(){const p=this.user();return this.students().filter(s=>(p.childIds||[]).includes(s.id));},
 parentHome(){const kids=this.parentChildren();return `${this.head('Family Growth Window','Parent view of child progress, storybook evidence, and home practice.')}<div class="grid three">${kids.map(k=>{const ev=this.data.evidence.filter(e=>e.studentId===k.id);return `<div class="card"><h2>${k.avatar} ${esc(k.name)}</h2><p><b>Points:</b> ${this.points(k.id)}</p><p><b>Evidence:</b> ${ev.length}</p><p>${this.aiStudentHint(k.id,this.studentTheme(k.id).id)}</p></div>`}).join('')}</div>`;},
 parentStorybook(){const kids=this.parentChildren();const ev=this.data.evidence.filter(e=>kids.some(k=>k.id===e.studentId));return `${this.head('Storybook View','Family-safe view of selected child voice, writing, drawing, and story evidence.')}<div class="grid two">${ev.map(e=>this.evidenceCardWithStudent(e)).join('')||'<div class="empty">No storybook evidence yet.</div>'}</div>`;},
 parentPractice(){const kids=this.parentChildren();return `${this.head('Home Practice AI','Simple 5-minute parent-child practice cards generated from current child quests.')}<div class="grid two">${kids.map(k=>{const t=this.studentTheme(k.id);return `<div class="card"><h2>${k.avatar} ${esc(k.name)}</h2><p><b>Current theme:</b> ${t.icon} ${esc(t.title)}</p><ol><li>Ask your child to listen and repeat: ${esc(t.words.slice(0,3).join(', '))}.</li><li>Point to one object and say: ${esc(t.writingFrame.replace('___',t.words[0]))}</li><li>Let your child draw one object and label it.</li><li>Celebrate effort with one star or sticker.</li></ol><button class="primary-btn" onclick="App.speakText('${esc(t.words.slice(0,3).join('. '))}')">Play Practice Words</button></div>`}).join('')}</div>`;},
 parentReport(){return `${this.head('Growth Report','Positive integrated-skill summary for parents.')}<div class="grid two">${this.parentChildren().map(k=>{const ev=this.data.evidence.filter(e=>e.studentId===k.id);return `<div class="card"><h2>${k.avatar} ${esc(k.name)}</h2><p>${esc(k.name)} is learning English through listening, speaking, reading, writing, drawing, and game-based quests. The portfolio currently contains ${ev.length} evidence items.</p><p><b>Recommended support:</b> Practice one short sentence every day and listen to the child’s voice recording together.</p></div>`}).join('')}</div>`;},
 adminPage(page){if(page==='home')return this.adminHome();if(page==='users')return this.adminUsers();if(page==='contents')return this.adminContents();if(page==='quests')return this.adminQuests();if(page==='safety')return this.adminSafety();if(page==='analytics')return this.adminAnalytics();if(page==='settings')return this.adminSettings();return '';},
 adminHome(){return `${this.head('Admin Control Center','PIN-protected full control for users, content, quests, safety, analytics, and settings.')}<div class="grid four"><div class="card metric"><div class="metric-icon">👥</div><div><b>${this.data.users.length}</b><span>Users</span></div></div><div class="card metric"><div class="metric-icon">🧰</div><div><b>${this.data.themes.length}</b><span>Content Themes</span></div></div><div class="card metric"><div class="metric-icon">🗺️</div><div><b>${this.data.quests.length}</b><span>Quests</span></div></div><div class="card metric"><div class="metric-icon">📚</div><div><b>${this.data.evidence.length}</b><span>Evidence</span></div></div></div><div class="card" style="margin-top:16px"><h2>Main Areas Status</h2><div class="grid three">${['SoundQuest AI: active audio play/stop and listening tasks','EchoMirror AI: active microphone recording and playback','GlyphPath AI: active reading cards and sentence path','StoryForge AI: active canvas, tiles, and writing evidence','Teacher Cockpit: active reports, content, analytics','Admin Control: active CRUD, safety, settings'].map(x=>`<div class="admin-block"><span class="badge ok">Working</span><h3>${esc(x)}</h3></div>`).join('')}</div></div>`;},
 adminUsers(){return `${this.head('User Management','Create, approve, delete, and control role-based dashboards.')}<div class="grid two"><div class="card"><h2>Add User</h2><div class="form-grid"><div class="field"><label>Name</label><input id="uName"></div><div class="field"><label>Email</label><input id="uEmail" type="email"></div><div class="field"><label>Password</label><input id="uPass" value="kidora2026"></div><div class="field"><label>Role</label><select id="uRole"><option>student</option><option>teacher</option><option>parent</option></select></div><div class="field"><label>Avatar</label><input id="uAvatar" value="🧒"></div></div><button class="primary-btn" onclick="App.addUser()">Add User</button></div><div class="card"><h2>All Users</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Role</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>${this.data.users.map(u=>`<tr><td>${u.avatar||''} ${esc(u.name)}</td><td>${esc(u.role)}</td><td>${esc(u.email)}</td><td><span class="badge ${u.status==='approved'?'ok':'warn'}">${esc(u.status)}</span></td><td><button class="mini-btn" onclick="App.toggleUser('${u.id}')">Toggle</button> <button class="danger-btn" onclick="App.deleteUser('${u.id}')">Delete</button></td></tr>`).join('')}</tbody></table></div></div></div>`;},
 addUser(){const name=$('uName').value.trim(),email=$('uEmail').value.trim(),password=$('uPass').value.trim(),role=$('uRole').value,avatar=$('uAvatar').value.trim();if(!name||!email||!password){this.toast('Complete name, email, and password.');return;}const id=uid(role);this.data.users.push({id,role,name,email,password,avatar,status:'approved',classId:'class1'});if(role==='student'){this.data.progress[id]={points:0,badges:[],completed:[],currentTheme:'colors'};this.data.classes[0].studentIds.push(id);}this.save();this.toast('User added.');this.renderDashboard('admin','users');},
 toggleUser(id){const u=this.data.users.find(x=>x.id===id);if(u){u.status=u.status==='approved'?'pending':'approved';this.save();this.renderDashboard('admin','users');}},
 deleteUser(id){if(!confirm('Delete this user?'))return;this.data.users=this.data.users.filter(u=>u.id!==id);delete this.data.progress[id];this.data.evidence=this.data.evidence.filter(e=>e.studentId!==id);this.save();this.renderDashboard('admin','users');},
 adminContents(){return this.teacherContent().replace('Content Studio','Admin Content Control').replace('Add Theme</button>','Add Theme</button>')+`<div class="card" style="margin-top:16px"><h2>Delete Content</h2><div class="content-list">${this.data.themes.map(t=>`<div class="content-item"><div><strong>${t.icon} ${esc(t.title)}</strong><span>${t.words.join(', ')}</span></div><button class="danger-btn" onclick="App.deleteTheme('${t.id}')">Delete</button></div>`).join('')}</div></div>`;},
 deleteTheme(id){if(this.data.themes.length<=1){this.toast('At least one theme is required.');return;}if(!confirm('Delete this theme and related quests?'))return;this.data.themes=this.data.themes.filter(t=>t.id!==id);this.data.quests=this.data.quests.filter(q=>q.themeId!==id);Object.values(this.data.progress).forEach(p=>{if(p.currentTheme===id)p.currentTheme=this.data.themes[0].id;});this.save();this.renderDashboard('admin','contents');},
 adminQuests(){return `${this.head('Quest Library Control','Approve, publish, delete, and review all integrated learning quests.')}<div class="content-list">${this.data.quests.map(q=>`<div class="content-item"><div><strong>${esc(q.title)}</strong><span>${esc(q.level)} • ${esc(q.status)} • ${esc(q.description)}</span></div><div><button class="mini-btn" onclick="App.toggleQuest('${q.id}')">Toggle Status</button> <button class="danger-btn" onclick="App.deleteQuest('${q.id}')">Delete</button></div></div>`).join('')}</div>`;},
 toggleQuest(id){const q=this.data.quests.find(x=>x.id===id);if(q){q.status=q.status==='approved'?'draft':'approved';this.save();this.renderDashboard('admin','quests');}},
 deleteQuest(id){if(!confirm('Delete quest?'))return;this.data.quests=this.data.quests.filter(q=>q.id!==id);this.save();this.renderDashboard('admin','quests');},
 adminSafety(){return `${this.head('AI Safety Review','Approve or reject generated AI content before children use it.')}<div class="grid two">${this.data.safetyQueue.map(s=>`<div class="card"><span class="badge ${s.status==='approved'?'ok':s.status==='rejected'?'bad':'warn'}">${esc(s.status)}</span><h2>${esc(s.title)}</h2><p>${esc(s.content)}</p><p><b>Created by:</b> ${esc(s.createdBy)} • ${esc(s.date)}</p><div class="activity-row"><button class="primary-btn" onclick="App.setSafety('${s.id}','approved')">Approve</button><button class="danger-btn" onclick="App.setSafety('${s.id}','rejected')">Reject</button></div></div>`).join('')||'<div class="empty">No AI content waiting for review.</div>'}</div>`;},
 setSafety(id,status){const s=this.data.safetyQueue.find(x=>x.id===id);if(s){s.status=status;this.save();this.renderDashboard('admin','safety');}},
 adminAnalytics(){return this.teacherAnalytics().replace('Research Cockpit','Admin Analytics and Export');},
 adminSettings(){const st=this.data.settings;return `${this.head('System Settings','Control admin PIN, copyright, school label, voice recording, and demo reset.')}<div class="grid two"><div class="card"><h2>Application Settings</h2><div class="form-grid"><div class="field"><label>Admin PIN</label><input id="setPin" value="${esc(st.adminPin)}"></div><div class="field"><label>School / Lab Name</label><input id="setSchool" value="${esc(st.schoolName)}"></div><div class="field"><label>Copyright Text</label><input id="setCopyright" value="${esc(st.copyright)}"></div><div class="field"><label>Voice Recording</label><select id="setVoice"><option value="true" ${st.voiceRecording?'selected':''}>Enabled</option><option value="false" ${!st.voiceRecording?'selected':''}>Disabled</option></select></div></div><button class="primary-btn" onclick="App.saveSettings()">Save Settings</button></div><div class="card"><h2>Danger Zone</h2><p>Reset restores complete seeded content, users, skills, dashboards, and portfolio examples.</p><button class="danger-btn" onclick="App.resetData()">Reset Demo Data</button></div></div>`;},
 saveSettings(){this.data.settings.adminPin=$('setPin').value.trim()||'2026';this.data.settings.schoolName=$('setSchool').value.trim();this.data.settings.copyright=$('setCopyright').value.trim();this.data.settings.voiceRecording=$('setVoice').value==='true';this.save();this.toast('Settings saved.');this.renderDashboard('admin','settings');},
 resetData(){if(!confirm('Reset all KIDORA Quest data to complete seeded version?'))return;this.data=defaultData();this.save();this.toast('Demo data reset.');this.renderDashboard('admin','home');},
 exportCSV(){const rows=[['date','student','type','theme','title','score','total','note'],...this.data.evidence.map(e=>[e.date,this.data.users.find(u=>u.id===e.studentId)?.name||'',e.type,this.theme(e.themeId).title,e.title,e.score,e.total,e.note])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kidora_quest_evidence_export.csv';a.click();URL.revokeObjectURL(a.href);this.toast('CSV exported.');}
};
window.App=App;
document.addEventListener('DOMContentLoaded',()=>App.init());
})();
